"""Constants for drug name normalization and parsing."""

CONNECTOR_WORDS = frozenset({"AND", "WITH", "OF", "THE"})

FORM_WORDS = frozenset({
    "TABLET", "TABLETS", "TAB", "TABS", "CAP", "CAPS", "CAPSULE", "CAPSULES",
    "SACHET", "SACHETS", "SACH", "AMP", "AMPS", "AMPOULE", "AMPOULES",
    "VIAL", "VIALS", "SUPP", "SUPPS", "PIECE", "PIECES", "DROPS", "DROP",
    "PEN", "PENS", "CARTRIDGE", "CARTRIDGES", "GUMMIES", "PACKETS", "DOSES",
    "BOTTLES", "EFF", "EFFERVESCENT", "F.C.TAB", "F.C.TABS", "F.C. TAB",
    "F.C. TABS", "F.C.TAB.", "F.C.TABS.", "E.C.TAB", "E.C.TABS", "E.C. TAB",
    "E.C. TABS", "EXT.REL.TAB", "EXT. REL. TABS", "E.R.F.C.TABS", "CHEW.TAB",
    "CHEWABLE TAB", "SUGAR COATED TAB", "S.G.CAPS", "S.G. CAPS", "H.G.CAPS",
    "H.G. CAPS", "ORODISSOLVABLE", "FILM", "FILMS", "LOZENGES"
})

FORM_PREFIXES = frozenset({
    "CREAM", "GEL", "OINTMENT", "OINT", "SYRUP", "SUSP", "SPRAY", "POWDER",
    "LOTION", "SOAP", "SHAMPOO", "OIL", "SERUM", "EMULGEL", "INJECTION",
    "INFUSION", "SOLUTION", "SOLN", "TOPICAL", "ORAL", "EYE", "NASAL", "EAR",
    "INTIMATE", "MASSAGE", "FEMININE", "CLEANSER", "WASH", "DOUCHE", "INHALER",
    "INH", "OPHTALMIC", "DROPS", "SPRAYS", "ORL", "SYRP", "SYP", "SUSPENSION",
    "EMULSION", "ENEMA", "MOUTHWASH"
})

NOISE_WORDS = frozenset({
    "BLUE", "RED", "WHITE", "ORS", "FLAVOR", "FLAVOUR", "LIQUID", "FACIAL", "MILK"
})

CRITICAL_CHEMICALS = frozenset({
    "POTASSIUM", "CALCIUM", "SODIUM", "MAGNESIUM", "IRON", "ZINC", "CETAL",
    "DOLIPRANE", "PANADOL", "ADOL", "PARAMOL"
})

SOFT_BRAND_DESCRIPTORS = frozenset({
    "ACTIVE", "ADULT", "ADULTS", "ANISE", "ANTISEPTIC", "COLD", "FLU", "FOLIC",
    "JOINT", "NIGHT", "ORIGINAL", "SINUS", "TOP", "TRIPLE", "VAG", "VAGINAL"
})

BRAND_QUALIFIERS = frozenset({
    "INFINITY", "SURACTIVE", "ALKALINE", "ESOMEPRAZOLE", "OPHTALMIC", "HAIR",
    "GROWTH", "CAFFEINE", "RICH", "DS", "DA", "ANTI", "EXTRA", "FORTE", "FORET",
    "EFFOX", "LONG", "EMOLLIENT", "OPHTIOLE", "ORL", "AMOUN", "PAEDIATRIC",
    "PEDIATRIC", "INFANT", "INFANTS", "INFANTILE", "KID", "KIDS"
})

ACRONYM_BRANDS = frozenset({"AIG"})

FLAVOR_WORDS = frozenset({
    "APPLE", "BANANA", "BERRY", "CHERRY", "CHOCOLATE", "CLOVE", "COLA", "GRAPE",
    "GINGER", "LEMON", "MANGO", "MINT", "ORANGE", "PINEAPPLE", "RASPBERRY",
    "STRAWBERRY", "VANILLA"
})

COLOR_WORDS = frozenset({
    "BLACK", "BLUE", "BROWN", "GOLD", "GREEN", "GREY", "PINK", "PURPLE", "RED",
    "SILVER", "WHITE", "YELLOW"
})

VITAMIN_MODIFIERS = frozenset({"B1", "B2", "B6", "B12", "D3"})

CRITICAL_MODIFIERS = frozenset({
    "PLUS", "EXTRA", "ADVANCE", "FORTE", "NIGHT", "COLD", "SINUS", "D", "R",
    "MEN", "WOMEN", "MALE", "FEMALE", "XR", "XL", "SR", "CR", "MR", "ER", "DR",
    "PRONTO", "VAGINAL", "NASAL", "MOUTH", "CARE", "COLLEDGE", "MACRO", "EVA",
    "MAN", "MILGA"
})

BABY_FORMULA_MODIFIERS = frozenset({
    "LF", "HA", "AR", "PRE", "COMFORT", "SENSITIVE", "DIGEST", "IT", "AC", "EC",
    "PRO", "EXPERT", "OPTIPRO"
})

COSMETIC_WORDS = frozenset({
    "BODY", "CONCEALER", "COSMETIC", "CREAM", "DEODORANT", "DOUCHE", "EMULGEL",
    "GEL", "HAIR", "LOTION", "MASK", "MOUTH", "MOUTHWASH", "OIL", "SERUM",
    "SHAMPOO", "SOAP", "SPRAY", "SUN", "TONER", "WASH"
})

DEVICE_WORDS = frozenset({
    "BANDAGE", "CANULA", "CONDOM", "CONDOMS", "LANCET", "LANCETS", "NEBULIZER",
    "NEEDLE", "NEEDLES", "PATCH", "PATCHES", "STRIP", "STRIPS", "SYRINGE", "SYRINGES"
})

BABY_FOOD_WORDS = frozenset({
    "APTAMIL", "BEBELAC", "BEBEJUNIOR", "CERELAC", "FEH", "HERO", "MILK", "NAN",
    "NIDO", "S26"
})

SUPPLEMENT_WORDS = frozenset({
    "ASHWAGANDHA", "BIOTIN", "CALCIUM", "CENTRUM", "COLLAGEN", "D3", "FEROGLOBIN",
    "GLUCOSAMINE", "OMEGA", "PERFECTIL", "PREGNACARE", "VITAMIN", "VITAMINS", "ZINC"
})

OCULAR_FORMS = frozenset({"OPHTALMIC", "EYE", "DROPS", "SOLUTION"})
LIQUID_FORMS = frozenset({"SYRUP", "SUSP", "SOLUTION", "ORL"})
LIQUID_DOSE_FORMS = frozenset({"SYRUP", "SUSP", "SOLUTION", "ORL", "AMP", "VIAL"})
SOLID_FORMS = frozenset({"TAB", "CAP"})

PEDIATRIC_WORDS = frozenset({
    "PAEDIATRIC", "PEDIATRIC", "INFANT", "INFANTS", "INFANTILE", "KID", "KIDS"
})
ADULT_WORDS = frozenset({"ADULT", "ADULTS"})

INFUSION_CONTEXT_WORDS = frozenset({
    "I", "V", "IV", "I/V", "INJ", "INJECTION", "INFUSION", "VIAL", "AMP", "AMPS"
})
ROUTE_WORDS = frozenset({"IM", "IV", "SC"})

FORM_SCAN_ORDER = (
    "VIAL", "VIALS", "AMPOULES", "AMPOULE", "AMP", "AMPS", "PENS", "PEN",
    "CARTRIDGES", "CARTIRIDGES", "CARTRIDGE", "SPRAY", "SPRAYS", "METERED",
    "SYRUP", "SYRP", "SYP", "SUSP", "OINTMENT", "OINT", "DROPS", "DROP", "EYE",
    "OPHTALMIC", "GEL", "CREAM", "POWDER", "SHAMPOO", "CLEANSER", "WASH",
    "SOLUTION", "SUPPS", "SUPP", "TABLETS", "TABLET", "TABS", "TAB", "CAPSULES",
    "CAPSULE", "CAPS", "CAP", "DOSES"
)
