"""GitHub models configuration for AI rotation."""

from __future__ import annotations

GITHUB_MODELS = (
    "meta/meta-llama-3.1-405b-instruct",
    "deepseek/deepseek-r1-0528",
    "deepseek/deepseek-r1",
    "deepseek/deepseek-v3-0324",
    "xai/grok-3",
    "meta/llama-4-scout-17b-16e-instruct",
    "openai/gpt-5",
    "openai/o3",
    "openai/o1",
    "openai/o1-preview",
    "meta/llama-3.3-70b-instruct",
    "ai21-labs/ai21-jamba-1.5-large",
    "cohere/cohere-command-a",
    "openai/gpt-4.1",
    "openai/gpt-4o",
    "xai/grok-3-mini",
    "openai/gpt-5-chat",
    "openai/gpt-5-mini",
    "mistral-ai/mistral-medium-2505",
    "meta/llama-4-maverick-17b-128e-instruct-fp8",
    "microsoft/phi-4-reasoning",
    "microsoft/phi-4",
    "openai/o4-mini",
    "openai/o3-mini",
    "openai/o1-mini",
    "cohere/cohere-command-r-plus-08-2024",
    "mistral-ai/mistral-small-2503",
    "openai/gpt-4.1-mini",
    "openai/gpt-4o-mini",
    "meta/llama-3.2-90b-vision-instruct",
    "openai/gpt-5-nano",
    "openai/gpt-4.1-nano",
    "microsoft/phi-4-multimodal-instruct",
    "meta/llama-3.2-11b-vision-instruct",
    "microsoft/phi-4-mini-reasoning",
    "mistral-ai/codestral-2501",
    "microsoft/phi-4-mini-instruct",
    "cohere/cohere-command-r-08-2024",
    "meta/meta-llama-3.1-8b-instruct",
    "mistral-ai/ministral-3b",
    "microsoft/mai-ds-r1",
)

__all__ = ["GITHUB_MODELS"]
