"""Cloudflare models configuration for AI rotation."""

from __future__ import annotations

CLOUDFLARE_MODELS = (
    "@cf/openai/gpt-oss-120b",
    "@cf/nvidia/nemotron-3-120b-a12b",
    "@cf/moonshotai/kimi-k2.6",
    "@cf/moonshotai/kimi-k2.5",
    "@cf/meta/llama-4-scout-17b-16e-instruct",
    "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    "@cf/qwen/qwen3-30b-a3b-fp8",
    "@cf/qwen/qwq-32b",
    "@cf/google/gemma-4-26b-a4b-it",
    "@cf/mistralai/mistral-small-3.1-24b-instruct",
    "@cf/qwen/qwen2.5-coder-32b-instruct",
    "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    "@cf/ibm-granite/granite-4.0-h-micro",
    "@cf/google/gemma-3-12b-it",
    "@cf/openai/gpt-oss-20b",
    "@cf/meta/llama-3.1-8b-instruct-fp8",
    "@cf/meta/llama-3.1-8b-instruct-awq",
    "@cf/meta/llama-3-8b-instruct",
    "@cf/meta/llama-3-8b-instruct-awq",
    "@cf/meta/llama-3.2-3b-instruct",
    "@cf/meta/llama-3.2-1b-instruct",
    "@cf/deepseek-ai/deepseek-math-7b-instruct",
    "@cf/zai-org/glm-4.7-flash",
    "@cf/mistral/mistral-7b-instruct-v0.1",
    "@cf/qwen/qwen1.5-14b-chat-awq",
    "@cf/qwen/qwen1.5-7b-chat-awq",
    "@cf/openchat/openchat-3.5-0106",
    "@cf/meta/llama-2-7b-chat-fp16",
    "@cf/meta/llama-2-7b-chat-int8",
    "@cf/microsoft/phi-2",
    "@cf/qwen/qwen1.5-1.8b-chat",
    "@cf/qwen/qwen1.5-0.5b-chat",
    "@cf/tinyllama/tinyllama-1.1b-chat-v1.0",
    "@cf/tiiuae/falcon-7b-instruct",
    "@hf/google/gemma-7b-it",
    "@hf/mistral/mistral-7b-instruct-v0.2",
    "@hf/nousresearch/hermes-2-pro-mistral-7b",
    "@hf/thebloke/llama-2-13b-chat-awq",
    "@hf/thebloke/mistral-7b-instruct-v0.1-awq",
    "@hf/thebloke/neural-chat-7b-v3-1-awq",
    "@hf/thebloke/openhermes-2.5-mistral-7b-awq",
    "@hf/thebloke/zephyr-7b-beta-awq",
    "@hf/nexusflow/starling-lm-7b-beta",
    "@hf/thebloke/deepseek-coder-6.7b-instruct-awq",
    "@cf/defog/sqlcoder-7b-2",
    "@cf/fblgit/una-cybertron-7b-v2-bf16",
    "@cf/thebloke/discolm-german-7b-v1-awq",
    "@hf/thebloke/deepseek-coder-6.7b-base-awq",
    "@cf/mistral/mistral-7b-instruct-v0.2-lora",
    "@cf/google/gemma-7b-it-lora",
    "@cf/google/gemma-2b-it-lora",
    "@cf/meta-llama/llama-2-7b-chat-hf-lora",
)

__all__ = ["CLOUDFLARE_MODELS"]
